version: "3.9"
services:
  docs:
    build: .
    image: dannyben/madness
    volumes:
      - ./docs:/docs
      - ./src:/docs/src
    ports:
      - 3000:3000
    command: server
  composer.install:
    image: composer/composer
    volumes:
      - $PWD:/app
    command: install
  project.tests.unit:
    image: composer/composer
    volumes:
      - $PWD:/app
    command: run-script tests
    depends_on:
      - composer.install
